### ISSUE TITLE
Reference to your module

### ISSUE THREAD

**Issue by pycckuu** [rnelsonchem/pHcalc#3]
Hey Ryan, I am using a slightly rewritten version of your pHcalc in my RTM framework and planning to add the framework as a chapter of my PhD thesis or supplemental information. Thus, I was wondering how should I cite your work? do you have a reference or DOI? At the moment I have only your name and link to the GitHub repository. Looking forward to your reply. 

RTM framework:
https://github.com/biogeochemistry/PorousMediaLab

**Comment by rnelsonchem** [comment]
Igor,

That is kind of you to reference my package. I think a web link would be
sufficient... However, it is not based on novel research; the systematic
approach to solving for pH is well documented. You may want to reference
Harris's "Quantitative Chemical Analysis", for example, which has a large
amount of info on the technique. In case my code were to disappear, someone
could still figure it out from the book.

Anyway, I'm glad you found it useful. Good luck with your thesis defense.

Ryan

**Comment by pycckuu** [comment]
Thanks Ryan! 

Wish you all the best.
