### ISSUE TITLE
pKa of carbonic acid

### ISSUE THREAD

**Issue by tp2750** [rnelsonchem/pHcalc#5]
In the [carbonic acid example](https://github.com/rnelsonchem/pHcalc#ph-of-001-m-h2co3) of the README, the pKa values of H2CO3 are given as [3.6, 10.32] and the pH of 0.01 M is computed to be 2.834.

According to [this list](https://chem.libretexts.org/Ancillary_Materials/Reference/Reference_Tables/Equilibrium_Constants/E1%3A_Acid_Dissociation_Constants_at_25C) the pKa values should be [6.35, 10.33]. 
Using these values gives a pH of 4.176 which is consistent with the value of 4.18 for 10 mM given [here](https://www.aqion.de/site/ph-of-common-acids).

Is it just a typo?

**Comment by mhvwerts** [comment]
According to Refs [1] and [2] (which are old, but whose results have been confirmed in more recent work), the pKa's of carbonic acid in water at 298K are indeed 6.35 and 10.33 (temperature-dependent). It must be a typo or an erroneous source.

[1] H. S. Harned, S. R. Scholes Jr. “The Ionization Constant of HC03- from 0 to 50°.” _J. Am. Chem. Soc._ **1941**, _63_,1706

[2] H. S. Harned, R. Davis. “The Ionization Constant of Carbonic Acid in Water and the Solubility of Carbon Dioxide in Water and Aqueous Salt Solutions from 0 to 50°.” _J. Am. Chem. Soc._ **1943**, _65_ , 2030

**Comment by rnelsonchem** [comment]
Fixed! Thanks so much @tp2750 and @mhvwerts for your close reading of the docs :)
